# Site settings
exclude: attic
title: VSXu - audio visualizer, music visualizer, visual programming language (VPL), realtime graphics design platform
subtitle: by Vovoid Media Technologies AB
email: youremailaddress@gmail.com
description: Experience music in <a href="/about/" onClick="analytics.trackDownloadEvent('home about');">new ways</a><br/>Visualize your music with VSXu<br/><br/><br/><a href="/documentation/changelog">v0.6.2</a> out now!<br/>(2017-05-19)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.vsxu.com" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:
current_version: v0.6.2
current_version_date: 2017-08-25
download_windows_url: https://github.com/vovoid/vsxu/releases/download/v0.6.2/VSXu_0.6.2_amd64.exe
download_linux_url: https://github.com/vovoid/vsxu/releases/download/v0.6.2/VSXu-0.6.2.glibc2.15.AppImage

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/VovoidMediaTech
github_url: https://github.com/vovoid/vsxu
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/VovoidMediaTech
twitch_url: https://www.twitch.tv/vmediatech
reddit_url: https://www.reddit.com/r/VSXu/
youtube_url: https://www.youtube.com/user/VSXu


# Build settings
markdown: kramdown

sass:
  style: compressed
